// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nizgesgdkiwkitlodxni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pemdlc2dka2l3a2l0bG9keG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNzg4OTAsImV4cCI6MjA4NDc1NDg5MH0.pEhWmHL6_TGxvw9uXfvOrxBA4heyik_1apMkJI08oDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});