// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksouedhhhxgtpxbzeqqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtzb3VlZGhoaHhndHB4YnplcXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODgyMDUsImV4cCI6MjA2NjA2NDIwNX0.ucpQTnthj_AnPLv4OD4RbR_azgpDMz-fk8ndZJMBp6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});